### ISSUE TITLE
arima.py的第65行多了个缩进

### ISSUE THREAD

**Issue by bearbro** [yuchengle/Arima#1]

**Comment by bearbro** [comment]
第67行最好改成 bic_matrix = pd.DataFrame(bic_matrix, dtype='float')

**Comment by zdy-code** [comment]
bic_matrix矩阵都为none是什么原因呢

**Comment by bearbro** [comment]
61报错跳到64行里喽，把try去掉看下具体的报错或者打断点debug一下 @zdy-code

**Comment by zdy-code** [comment]
你好，很感谢你能回复，把try注释掉，控制台出现了这个错误。我是python小白，所以不太明白，希望你可以帮忙解决下，万分感谢!

NotImplementedError: 
statsmodels.tsa.arima_model.ARMA and statsmodels.tsa.arima_model.ARIMA have
been removed in favor of statsmodels.tsa.arima.model.ARIMA (note the .
between arima and model) and statsmodels.tsa.SARIMAX.

statsmodels.tsa.arima.model.ARIMA makes use of the statespace framework and
is both well tested and maintained. It also offers alternative specialized
parameter estimators.

**Comment by zdy-code** [comment]
你好，很感谢你能回复，把try注释掉，控制台出现了这个错误。我是python小白，所以不太明白，希望你可以帮忙解决下，万分感谢!

NotImplementedError:
statsmodels.tsa.arima_model.ARMA and statsmodels.tsa.arima_model.ARIMA have
been removed in favor of statsmodels.tsa.arima.model.ARIMA (note the .
between arima and model) and statsmodels.tsa.SARIMAX.

statsmodels.tsa.arima.model.ARIMA makes use of the statespace framework and
is both well tested and maintained. It also offers alternative specialized
parameter estimators. @bearbro

**Comment by bearbro** [comment]
字面意思呀，导入错误，ARMA、ARIMA 两个类在新版本中被移除，然后用另外两个替代了
直接翻译软件翻译一下喽
降低版本或者去改代码喽，推荐去改代码
现成的解决方案百度一下应该也会有吧 @zdy-code

**Comment by bearbro** [comment]
只是想跑ARIMA的话，可以去看看👇这个，我觉得写的挺好
https://github.com/Jenniferz28/Time-Series-ARIMA-XGBOOST-RNN/blob/master/myArima.py
@zdy-code

**Comment by zdy-code** [comment]
好的，谢谢
